# Generated by Django 4.1 on 2022-11-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bider',
        ),
    ]
