# Generated by Django 4.1 on 2022-11-12 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_datecreated_comment_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='dateCreated',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dateCreated',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='listing',
            name='dateCreated',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
