# Generated by Django 4.1 on 2022-11-14 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_is_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lister',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lister', to=settings.AUTH_USER_MODEL),
        ),
    ]
